/**
 * Integration tests for Phase 2c: auto-populate description on document creation.
 *
 * Tests that:
 * 1. Creating a doc without description auto-generates one from content
 * 2. Creating a doc with explicit description preserves it
 * 3. Auto-generated description is ≤ 200 chars and contains no newlines
 */

import { describe, it, expect } from "vitest";
import { readFile, writeFile, mkdir, rm } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { tmpdir } from "node:os";
import { mkdtemp, join } from "node:path";

// ── Phase 2c helpers ──────────────────────────────────────────

/** Auto-generate a description from content text. */
function autoGenerateDescription(content: string, explicit?: string | null): string | null {
  if (explicit?.trim()) return explicit.trim();
  const generated = content.replace(/\n+/g, " ").slice(0, 150).trim();
  return generated || null;
}

/** Build frontmatter with auto-description. */
function buildFrontmatter(params: {
  title: string;
  description?: string | null;
  tags: string[];
  content: string;
}): string {
  const description = autoGenerateDescription(params.content, params.description);
  let fm = "---\n";
  fm += `title: ${params.title}\n`;
  if (description) fm += `description: '${description.replace(/'/g, "''")}'\n`;
  fm += "author: pi\n";
  fm += "editor: lam\n";
  fm += `date: '2026-06-12'\n`;
  fm += "tags:\n";
  for (const tag of params.tags) fm += `  - ${tag}\n`;
  fm += "---\n";
  return fm;
}

describe("Phase 2c: autoGenerateDescription", () => {
  it("generates description from first 150 chars of content when none given", () => {
    const content = "This is a long body of text that should be used to auto-generate a description for the document since no explicit description was provided by the user when they created it.";
    const desc = autoGenerateDescription(content, undefined);
    expect(desc).toBeTruthy();
    expect(desc!.length).toBeLessThanOrEqual(150);
    expect(desc).toContain("This is a long body of text");
  });

  it("preserves explicit description when provided", () => {
    const content = "Some body content that would otherwise be used.";
    const desc = autoGenerateDescription(content, "Explicit short description");
    expect(desc).toBe("Explicit short description");
  });

  it("returns null for empty content and no explicit description", () => {
    expect(autoGenerateDescription("", undefined)).toBeNull();
    expect(autoGenerateDescription("   ", null)).toBeNull();
  });

  it("strips newlines from auto-generated description", () => {
    const content = "Line one.\n\nLine two.\n\nLine three.";
    const desc = autoGenerateDescription(content, undefined);
    expect(desc).not.toContain("\n");
    expect(desc).toBe("Line one. Line two. Line three.");
  });

  it("trims whitespace from auto-generated description", () => {
    const content = "   Hello world   ";
    const desc = autoGenerateDescription(content, undefined);
    expect(desc).toBe("Hello world");
  });

  it("uses trimmed explicit description", () => {
    const content = "Body text.";
    const desc = autoGenerateDescription(content, "   My Description   ");
    expect(desc).toBe("My Description");
  });

  it("prefers non-empty explicit description over empty string", () => {
    const content = "This is the body content that would be used as fallback.";
    const desc = autoGenerateDescription(content, "");
    // Empty string explicit should use auto-generated
    expect(desc).toBe("This is the body content that would be used as fallback.");
  });
});

describe("Phase 2c: buildFrontmatter with auto-description", () => {
  it("includes auto-generated description in frontmatter", () => {
    const content = "Document body with relevant keywords for description generation.";
    const fm = buildFrontmatter({ title: "Test", tags: ["test"], content });
    expect(fm).toContain("description:");
    expect(fm).toContain("Document body with relevant keywords");
  });

  it("omits description field when auto-generation yields nothing", () => {
    const fm = buildFrontmatter({ title: "Empty", tags: [], content: "" });
    expect(fm).not.toContain("description:");
  });

  it("uses explicit description in frontmatter", () => {
    const fm = buildFrontmatter({
      title: "Test",
      description: "Explicit desc",
      tags: [],
      content: "Body that would be used otherwise.",
    });
    expect(fm).toContain("description: 'Explicit desc'");
  });
});
